-- Tipos de operación SUNAT con detracción (catálogo 51: 1001-1004).
-- codigos y campos son JSON: la pantalla carga el menú de bien/servicio al elegir el tipo.

CREATE TABLE IF NOT EXISTS `detracciones` (
    `codigo` VARCHAR(4) NOT NULL,
    `nombre` VARCHAR(240) NOT NULL,
    `codigos` JSON NOT NULL,
    `campos` JSON NOT NULL,
    `orden` INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (`codigo`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `detracciones` (`codigo`, `nombre`, `codigos`, `campos`, `orden`)
SELECT '1001', 'Operación sujeta al Sistema de Pago de Obligaciones Tributarias con el Gobierno Central', CAST('[{"codigo":"001","nombre":"Azúcar y melaza de caña","porcentaje":10},{"codigo":"003","nombre":"Alcohol etílico","porcentaje":10},{"codigo":"005","nombre":"Maíz amarillo duro","porcentaje":4},{"codigo":"007","nombre":"Caña de azúcar","porcentaje":10},{"codigo":"008","nombre":"Madera","porcentaje":4},{"codigo":"009","nombre":"Arena y piedra","porcentaje":10},{"codigo":"010","nombre":"Residuos, subproductos, desechos y chatarra","porcentaje":15},{"codigo":"011","nombre":"Bienes gravados con el IGV por renuncia a la exoneración","porcentaje":10},{"codigo":"012","nombre":"Intermediación laboral y tercerización","porcentaje":12},{"codigo":"014","nombre":"Carnes y despojos comestibles","porcentaje":4},{"codigo":"016","nombre":"Aceite de pescado","porcentaje":10},{"codigo":"017","nombre":"Harina, polvo y pellets de pescado","porcentaje":4},{"codigo":"019","nombre":"Arrendamiento de bienes","porcentaje":10},{"codigo":"020","nombre":"Mantenimiento y reparación de bienes muebles","porcentaje":12},{"codigo":"021","nombre":"Movimiento de carga","porcentaje":10},{"codigo":"022","nombre":"Otros servicios empresariales","porcentaje":12},{"codigo":"023","nombre":"Leche","porcentaje":4},{"codigo":"024","nombre":"Comisión mercantil","porcentaje":10},{"codigo":"025","nombre":"Fabricación de bienes por encargo","porcentaje":10},{"codigo":"030","nombre":"Contratos de construcción","porcentaje":4},{"codigo":"031","nombre":"Oro gravado con el IGV","porcentaje":10},{"codigo":"032","nombre":"Páprika y otros frutos capsicum o pimienta","porcentaje":10},{"codigo":"034","nombre":"Minerales metálicos no auríferos","porcentaje":10},{"codigo":"035","nombre":"Bienes exonerados del IGV","porcentaje":1.5},{"codigo":"036","nombre":"Oro y demás minerales metálicos exonerados del IGV","porcentaje":1.5},{"codigo":"037","nombre":"Demás servicios gravados con el IGV","porcentaje":12},{"codigo":"039","nombre":"Minerales no metálicos","porcentaje":10},{"codigo":"041","nombre":"Plomo","porcentaje":15}]' AS JSON), CAST('[]' AS JSON), 1
WHERE NOT EXISTS (SELECT 1 FROM `detracciones` WHERE `codigo` = '1001');

INSERT INTO `detracciones` (`codigo`, `nombre`, `codigos`, `campos`, `orden`)
SELECT '1002', 'Operación sujeta al Sistema de Pago de Obligaciones Tributarias con el Gobierno Central - Recursos Hidrobiológicos', CAST('[{"codigo":"004","nombre":"Recursos hidrobiológicos","porcentaje":4}]' AS JSON), CAST('[{"key":"matricula","label":"Matrícula de la embarcación pesquera","tipo":"text"},{"key":"nombre_embarcacion","label":"Nombre de la embarcación pesquera","tipo":"text","opcional":true},{"key":"especie","label":"Descripción del tipo de la especie vendida","tipo":"text","opcional":true},{"key":"lugar_descarga","label":"Lugar de descarga","tipo":"text","opcional":true},{"key":"cantidad_especie","label":"Cantidad de la especie vendida","tipo":"monto"},{"key":"fecha_descarga","label":"Fecha de descarga","tipo":"fecha"}]' AS JSON), 2
WHERE NOT EXISTS (SELECT 1 FROM `detracciones` WHERE `codigo` = '1002');

INSERT INTO `detracciones` (`codigo`, `nombre`, `codigos`, `campos`, `orden`)
SELECT '1003', 'Operación sujeta al Sistema de Pago de Obligaciones Tributarias con el Gobierno Central - Servicio de Transporte de Pasajeros', CAST('[{"codigo":"026","nombre":"Servicio de transporte de personas","porcentaje":10}]' AS JSON), CAST('[]' AS JSON), 3
WHERE NOT EXISTS (SELECT 1 FROM `detracciones` WHERE `codigo` = '1003');

INSERT INTO `detracciones` (`codigo`, `nombre`, `codigos`, `campos`, `orden`)
SELECT '1004', 'Operación sujeta al Sistema de Pago de Obligaciones Tributarias con el Gobierno Central - Servicio de Transporte de Carga', CAST('[{"codigo":"027","nombre":"Servicio de transporte de carga","porcentaje":4}]' AS JSON), CAST('[{"key":"origen_ubigeo","label":"Ubigeo de origen","tipo":"text"},{"key":"origen_direccion","label":"Dirección de origen","tipo":"text"},{"key":"destino_ubigeo","label":"Ubigeo de destino","tipo":"text"},{"key":"destino_direccion","label":"Dirección de destino","tipo":"text"},{"key":"detalle_viaje","label":"Detalle del viaje","tipo":"text"},{"key":"registro_mtc","label":"Registro MTC","tipo":"text"},{"key":"configuracion_vehicular","label":"Configuración vehicular","tipo":"text","ayuda":"Tipo de camión. Ejemplo: C3"},{"key":"carga_util_tm","label":"Carga útil en toneladas métricas del vehículo","tipo":"monto","defecto":"0.00"},{"key":"valor_referencial_servicio","label":"Valor referencial del servicio de transporte (S/)","tipo":"monto","ayuda":"El precio del flete."},{"key":"valor_referencial","label":"Valor referencial en función a la carga efectiva (S/)","tipo":"monto","opcional":true,"defecto":"0.00"},{"key":"valor_referencial_nominal","label":"Valor referencial en función a la carga útil nominal (S/)","tipo":"monto","opcional":true,"defecto":"0.00"},{"key":"retorno_vacio","label":"Indicador de retorno al vacío","tipo":"sino","defecto":"si"}]' AS JSON), 4
WHERE NOT EXISTS (SELECT 1 FROM `detracciones` WHERE `codigo` = '1004');
